#!/usr/bin/env python3
"""
Command-line wrapper for exporting PyTorch models to TorchScript (.pt) format for FTorch.
"""

import os
import sys

_CTSM_PYTHON = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                            os.pardir,
                            os.pardir,
                            'python')
sys.path.insert(1, _CTSM_PYTHON)

from ctsm.machine_learning.export_torchscript import main

if __name__ == "__main__":
    main()
